# Generated by Django 3.2.8 on 2021-11-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_chw',
            field=models.BooleanField(default=False, verbose_name='student status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_org',
            field=models.BooleanField(default=False, verbose_name='teacher status'),
        ),
    ]
